# Generated by Django 4.0.2 on 2022-02-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasingpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_type', models.CharField(max_length=30)),
                ('container_history', models.CharField(max_length=30)),
            ],
        ),
    ]
