# Generated by Django 4.0.2 on 2022-02-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasingpage', '0002_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
