# Generated by Django 4.0.2 on 2022-02-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasingpage', '0003_container_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='lesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
