# Generated by Django 4.0.2 on 2022-02-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasingpage', '0004_lesse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='lessor',
        ),
    ]
