# Generated by Django 4.0.1 on 2022-03-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasingpage', '0005_rename_register_lessor'),
    ]

    operations = [
        migrations.CreateModel(
            name='leasinglist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
