# Generated by Django 4.0.1 on 2022-03-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasingpage', '0006_leasinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasinglist',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leasinglist',
            name='years',
            field=models.IntegerField(default=1),
        ),
    ]
