# Generated by Django 4.0.1 on 2022-03-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasingpage', '0007_leasinglist_amount_leasinglist_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasinglist',
            name='amount',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
