# Generated by Django 4.0.1 on 2022-03-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasingpage', '0008_alter_leasinglist_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasinglist',
            name='containers_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leasinglist',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
